// trackit/src/components/Navbar.vue
<template>
  <nav class="w-full bg-[var(--color-background)] text-[var(--color-headings)] shadow-md p-4 flex justify-between items-center border-b border-[var(--color-border)]">
    <!-- Logo -->
    <div class="flex items-center">
      <img src="../assets/trackit.png" alt="TrackIt Logo" class="h-8">
    </div>

    <!-- Desktop Navigation -->
    <div v-if="user" class="hidden md:flex space-x-6 justify-center">
      <router-link to="/" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">Projects</router-link>
      <router-link to="/sprintboard" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">Sprint Board</router-link>
      <router-link to="/kanban" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">Kanban</router-link>
    </div>

    <!-- Right Side -->
    <div class="hidden md:flex items-center space-x-4">
      <div v-if="user" class="relative">
        <button @click="toggleDropdown" class="flex items-center justify-center w-8 h-8 bg-[var(--color-primary)] text-white rounded-full text-sm">
          {{ userInitials }}
        </button>
        <div v-if="isDropdownOpen" class="absolute right-0 mt-2 w-48 bg-[var(--color-background)] border border-[var(--color-border)] shadow-lg rounded-lg">
          <router-link to="/account" class="block px-4 py-2 text-sm font-bold hover:bg-[var(--color-highlights)]">Account</router-link>
          <router-link to="/progressboard" class="block px-4 py-2 text-sm font-bold hover:bg-[var(--color-highlights)]">Progress Board</router-link>
          <button @click="logout" class="block w-full px-4 py-2 text-sm font-bold text-left hover:bg-[var(--color-highlights)]">Logout</button>
        </div>
      </div>

      <!-- Login Button (Opens Modal) -->
      <button v-else @click="showLoginModal = true" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">
        Login
      </button>

      <!-- Themes (Hidden when logged out) -->
      <router-link v-if="user" to="/themeselector" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">Themes</router-link>
    </div>

    <!-- Mobile Menu Button -->
    <button @click="toggleMenu" class="md:hidden text-2xl text-[var(--color-headings)] hover:text-[var(--color-highlights)] transition duration-300 cursor-pointer">
      ☰
    </button>
  </nav>

  <!-- Mobile Menu -->
  <div v-if="isMenuOpen" class="md:hidden flex flex-col items-center space-y-2 p-4 bg-[var(--color-background)] border-t border-[var(--color-border)] text-[var(--color-headings)] shadow-lg">
    <template v-if="user">
      <router-link to="/" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer" @click="toggleMenu">Projects</router-link>
      <router-link to="/sprintboard" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer" @click="toggleMenu">Sprint Board</router-link>
      <router-link to="/kanban" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer" @click="toggleMenu">Kanban</router-link>
      <router-link to="/progressboard" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer" @click="toggleMenu">Progress Board</router-link>
      <router-link to="/themeselector" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer" @click="toggleMenu">Themes</router-link>
    </template>

    <!-- Login/Logout for Mobile -->
    <button v-if="!user" @click="showLoginModal = true" class="font-bold hover:text-[var(--color-highlights)] hover:underline transition duration-300 cursor-pointer">Login</button>
    <button v-else @click="logout" class="font-bold text-[var(--color-headings)] hover:text-[var(--color-highlights)] transition duration-300 cursor-pointer">Logout</button>
  </div>

  <!-- Login Modal -->
  <LoginModal :isOpen="showLoginModal" :closeModal="() => (showLoginModal = false)" />
</template>


<script>
import { ref, onMounted } from "vue";
import { auth } from '../firebaseConfig';
import LoginModal from "./LoginModal.vue";
import { useRouter } from "vue-router";

export default {
  components: { LoginModal },
  setup() {
    const isMenuOpen = ref(false);
    const isDropdownOpen = ref(false);
    const user = ref(null);
    const userInitials = ref("");
    const showLoginModal = ref(false);
    const router = useRouter();

    const toggleMenu = () => {
      isMenuOpen.value = !isMenuOpen.value;
    };

    const toggleDropdown = () => {
      isDropdownOpen.value = !isDropdownOpen.value;
    };

    const logout = async () => {
      await auth.signOut();
      user.value = null;
      router.push("/auth"); // Redirect to /auth after logout
    };

    onMounted(() => {
      auth.onAuthStateChanged((authUser) => {
        if (authUser) {
          user.value = authUser;
          if (authUser.displayName) {
            // Use initials from display name
            userInitials.value = authUser.displayName
              .split(" ")
              .map(n => n[0])
              .join("")
              .toUpperCase();
          } else if (authUser.email) {
            // Use first letter of email if no display name
            userInitials.value = authUser.email[0].toUpperCase();
          }
        } else {
          user.value = null;
          userInitials.value = "U"; // Default back to "U"
        }
      });
    });

    return { isMenuOpen, toggleMenu, isDropdownOpen, toggleDropdown, user, userInitials, logout, showLoginModal  };
  }
};
</script>

<style scoped>
nav {
  transition: background-color 0.3s ease-in-out;
}
</style>

// trackit/app/components/navbar.tsx
"use client";

import { useState, useEffect } from "react";
import { useTheme } from "./theme-provider";
import { Sun, Moon, Search, ChevronDown } from "lucide-react";
import Image from "next/image";
import logo from "../components/images/logo.png";
import { useRouter } from "next/navigation";
import { auth } from "../lib/firebase"; // ✅ your auth instance
import { onAuthStateChanged, signOut, type User } from "firebase/auth";

export default function Navbar() {
  const { theme, toggleTheme } = useTheme();
  const router = useRouter();

  // State for Firebase user
  const [user, setUser] = useState<User | null>(null);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  // Listen for auth state changes
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
    });
    return () => unsubscribe();
  }, []);

  const handleLogout = async () => {
    await signOut(auth);
    router.push("/login");
  };

  const userEmail = user?.email || "User";
  const userInitial = userEmail.charAt(0).toUpperCase();

  return (
    <nav className="flex items-center justify-between px-6 py-2 border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 transition-colors shadow-sm relative">
      {/* Left: Logo */}
      <div className="flex items-center gap-2">
        <Image src={logo} alt="TrackIt Logo" width={48} height={48} />
      </div>

      {/* Center: Search */}
      <div className="mx-6 w-80">
        <div className="relative">
          <input
            type="text"
            placeholder="Search projects or tasks..."
            className="w-full py-1.5 pl-10 pr-4 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100 placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 transition-colors"
          />
          <Search
            className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 dark:text-gray-400"
            size={18}
          />
        </div>
      </div>

      {/* Right: Theme toggle + User */}
      <div className="flex items-center gap-4 relative">
        <button
          onClick={toggleTheme}
          className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors text-gray-700 dark:text-gray-200"
        >
          {theme === "light" ? <Moon size={18} /> : <Sun size={18} />}
        </button>

        {/* User Dropdown */}
        <div className="relative">
          <button
            onClick={() => setIsDropdownOpen(!isDropdownOpen)}
            className="flex items-center gap-2 px-3 py-1 rounded-full bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-all text-gray-700 dark:text-gray-200 font-semibold"
          >
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-500 text-white text-sm font-bold">
              {userInitial}
            </span>
            <ChevronDown size={14} />
          </button>

          {isDropdownOpen && (
            <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg z-10">
              <div className="px-4 py-2 text-sm text-gray-700 dark:text-gray-300 border-b border-gray-100 dark:border-gray-700">
                {userEmail}
              </div>
              <button
                onClick={() => router.push("/account")}
                className="w-full text-left px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700"
              >
                Account
              </button>
              <button
                onClick={handleLogout}
                className="w-full text-left px-4 py-2 text-sm text-red-600 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700"
              >
                Logout
              </button>
            </div>
          )}
        </div>
      </div>
    </nav>
  );
}
